export const INCREMENT = 'INCREMENT'
export const GET_ROUTES = 'GET_ROUTES'
export const SAVE_ROUTE = 'SAVE_ROUTE'
export const SELECT_ROUTE = 'SELECT_ROUTE'
export const GET_ROUTE = 'GET_ROUTE'
export const UPDATE_ROUTE = 'UPDATE_ROUTE'
